# Generated by Django 3.2 on 2021-04-18 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created1',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 42, 37, 827473)),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created2',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
		migrations.AddField(
            model_name='movie',
            name='date_created5',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 42, 37, 827512, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created3',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 42, 37, 827554, tzinfo=utc)),
        ),
		migrations.RenameField(
            model_name='movie',
            old_name='date_created',
            new_name='date_created4'
        ),
        
    ]
