# Generated by Django 3.2 on 2021-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210418_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_created4',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created5',
        ),
    ]
